import os
import google.generativeai as genai
from app.rag.retriever import retrieve_context
from app.ai.gemini_classifier import api_key

# Configure Gemini if key is available
if api_key:
    genai.configure(api_key=api_key)

def ask_question(query: str, chat_history: list = None) -> str:
    """
    Answers a user question regarding their transaction history using RAG.
    
    Parameters:
    - query: The user's question string.
    - chat_history: Optional list of prior messages/turns.
    
    Returns:
    - String response generated by Gemini AI model or fallback retriever.
    """
    # 1. Retrieve relevant transactions as context
    context = retrieve_context(query, k=15)
    
    # 2. Check if Gemini API is available
    if not api_key:
        # Graceful fallback: return matched transactions directly in a structured format
        fallback_msg = (
            "⚠️ **Gemini API Key not set.** Here is a list of relevant transactions matching your query:\n\n"
        )
        if "No transaction history" in context or "No matching transactions" in context:
            return fallback_msg + "*No matching transactions found in your statement.*"
        
        for line in context.split("\n"):
            fallback_msg += f"- {line}\n"
        return fallback_msg

    try:
        # Prepare Chat History formatting
        history_context = ""
        if chat_history:
            history_context = "Conversation History:\n"
            for msg in chat_history[-6:]:  # Keep last 3 turns
                role = "User" if msg.get("sender") == "user" else "Assistant"
                text = msg.get("text", "")
                history_context += f"{role}: {text}\n"
            history_context += "\n"

        prompt = f"""
You are Cortex AI, a highly intelligent financial assistant for Cortex Finance.
Your task is to answer user queries about their bank statement transactions using the retrieved context below.

{history_context}
Retrieved Bank Transaction Context:
\"\"\"
{context}
\"\"\"

User Question: "{query}"

Instructions:
- Provide a direct, clear, and professional response.
- Use markdown tables, bolding, or lists for financial statistics or breakdowns.
- Cite specific dates and amounts from the context.
- If no transactions are found or context is empty, politely inform the user that you couldn't find any relevant transactions.
"""

        model = genai.GenerativeModel("gemini-1.5-flash")
        response = model.generate_content(prompt)
        return response.text.strip()
        
    except Exception as e:
        print(f"Error calling Gemini in chatbot: {e}")
        # Fallback to presenting the context directly
        return f"Error connecting to AI assistant. Here is the transaction data we found:\n\n{context}"